import { useEffect } from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";

import {
  AmbientBackground,
  colors,
  CutFlashes,
  fonts,
  ProgressRail,
  SceneShell,
  useFontsReady,
  Vignette,
} from "./video/kit";
import { DashboardScene } from "./video/scenes/Dashboard";
import { EndScene } from "./video/scenes/End";
import { HookScene } from "./video/scenes/Hook";
import { InstallScene } from "./video/scenes/Install";
import { MenuScene } from "./video/scenes/Menu";
import { ResizeScene } from "./video/scenes/Resize";
import { TreeScene } from "./video/scenes/Tree";

/**
 * 870 frames @ 30fps = 29s, cut on a 120 BPM grid (60-frame bars).
 * Hook 0–120 · Resize 120–300 · Menu 300–420 · Tree 420–540 ·
 * Install 540–660 · Dashboard 660–780 · End 780–870.
 * The soundtrack in public/music.wav is
 * generated by scripts/make-music.mjs on the same grid.
 */
export const LaunchVideo = () => {
  useFontsReady();

  useEffect(() => {
    const root = document.documentElement;
    const wasDark = root.classList.contains("dark");
    root.classList.add("dark");

    return () => {
      if (!wasDark) {
        root.classList.remove("dark");
      }
    };
  }, []);

  return (
    <AbsoluteFill
      style={{
        backgroundColor: colors.background,
        color: colors.text,
        fontFamily: fonts.sans,
        overflow: "hidden",
      }}
    >
      <Audio src={staticFile("music.wav")} />
      <AmbientBackground />

      <Sequence durationInFrames={120} name="01 Hook">
        <SceneShell duration={120}>
          <HookScene />
        </SceneShell>
      </Sequence>
      <Sequence from={120} durationInFrames={180} name="02 Resize demo">
        <SceneShell duration={180}>
          <ResizeScene />
        </SceneShell>
      </Sequence>
      <Sequence from={300} durationInFrames={120} name="03 Collapsed menu">
        <SceneShell duration={120}>
          <MenuScene />
        </SceneShell>
      </Sequence>
      <Sequence from={420} durationInFrames={120} name="04 Tree navigation">
        <SceneShell duration={120} out="fade">
          <TreeScene />
        </SceneShell>
      </Sequence>
      <Sequence from={540} durationInFrames={120} name="05 Install">
        <SceneShell duration={120}>
          <InstallScene />
        </SceneShell>
      </Sequence>
      <Sequence from={660} durationInFrames={120} name="06 Dashboard reveal">
        <SceneShell duration={120}>
          <DashboardScene />
        </SceneShell>
      </Sequence>
      <Sequence from={780} durationInFrames={90} name="07 End card">
        <SceneShell duration={90} out="none">
          <EndScene />
        </SceneShell>
      </Sequence>

      <CutFlashes cuts={[120, 300, 420, 540, 660, 780]} />
      <Vignette />
      <ProgressRail />
    </AbsoluteFill>
  );
};
